<a href="https://colab.research.google.com/github/KA18202005/DeepLearning-Learning/blob/pytorch/Pytorch_training_pipeline_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[ 1.25300081,  0.24065384,  1.22195008, ...,  0.50822876,
        -0.8836594 , -0.52160766],
       [-0.9221775 , -0.14668361, -0.90328555, ..., -0.54214199,
        -1.02525209, -0.35332277],
       [ 0.54968371, -0.31235204,  0.60135333, ...,  1.06838656,
         2.15114392,  2.13469639],
       ...,
       [-0.93068537, -1.60269907, -0.95465945, ..., -1.24503519,
        -1.19516332, -0.94259046],
       [ 0.72267703,  0.55332382,  0.72876061, ...,  0.99200141,
         3.08408242,  0.13421644],
       [-0.56484703, -0.93535865, -0.59011023, ..., -0.89126708,
        -0.38021873, -0.22940881]])

In [8]:
y_train

27     M
405    B
34     M
460    M
494    B
      ..
153    B
1      M
296    B
35     M
324    B
Name: diagnosis, Length: 455, dtype: object

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [11]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

In [14]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [19]:
learning_rate = 0.1
epochs = 50

In [20]:
# define loss function
loss_function = nn.BCELoss()

In [21]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5220301747322083
Epoch: 2, Loss: 0.42724138498306274
Epoch: 3, Loss: 0.37163689732551575
Epoch: 4, Loss: 0.3343810439109802
Epoch: 5, Loss: 0.30727463960647583
Epoch: 6, Loss: 0.2864386737346649
Epoch: 7, Loss: 0.2697831392288208
Epoch: 8, Loss: 0.25607413053512573
Epoch: 9, Loss: 0.24453212320804596
Epoch: 10, Loss: 0.23463809490203857
Epoch: 11, Loss: 0.22603201866149902
Epoch: 12, Loss: 0.2184552550315857
Epoch: 13, Loss: 0.21171671152114868
Epoch: 14, Loss: 0.2056717872619629
Epoch: 15, Loss: 0.20020869374275208
Epoch: 16, Loss: 0.19523951411247253
Epoch: 17, Loss: 0.1906939297914505
Epoch: 18, Loss: 0.1865149885416031
Epoch: 19, Loss: 0.1826559156179428
Epoch: 20, Loss: 0.17907799780368805
Epoch: 21, Loss: 0.17574873566627502
Epoch: 22, Loss: 0.17264066636562347
Epoch: 23, Loss: 0.16973042488098145
Epoch: 24, Loss: 0.16699793934822083
Epoch: 25, Loss: 0.16442587971687317
Epoch: 26, Loss: 0.16199922561645508
Epoch: 27, Loss: 0.1597047746181488
Epoch: 28, Loss: 0.1575310379266739
Epoch: 29, Loss: 0.15546774864196777
Epoch: 30, Loss: 0.15350592136383057
Epoch: 31, Loss: 0.15163752436637878
Epoch: 32, Loss: 0.149855375289917
Epoch: 33, Loss: 0.14815306663513184
Epoch: 34, Loss: 0.1465248018503189
Epoch: 35, Loss: 0.14496533572673798
Epoch: 36, Loss: 0.14346998929977417
Epoch: 37, Loss: 0.14203448593616486
Epoch: 38, Loss: 0.14065493643283844
Epoch: 39, Loss: 0.1393277645111084
Epoch: 40, Loss: 0.13804975152015686
Epoch: 41, Loss: 0.13681791722774506
Epoch: 42, Loss: 0.1356295347213745
Epoch: 43, Loss: 0.13448213040828705
Epoch: 44, Loss: 0.13337336480617523
Epoch: 45, Loss: 0.13230112195014954
Epoch: 46, Loss: 0.13126341998577118
Epoch: 47, Loss: 0.1302584409713745
Epoch: 48, Loss: 0.12928448617458344
Epoch: 49, Loss: 0.12834002077579498
Epoch: 50, Loss: 0.1274235099554062

In [22]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5584795475006104